### ISSUE TITLE
Error when uploading Singularity image to cluster

### ISSUE THREAD

**Issue by dtch1997** [ethanluoyc/lxm3#7] opened 2023-09-27 12:53 UTC
I encountered an error while using LXM3 to deploy images to the cluster. 

Command: 
```bash
$ LXM_CLUSTER=cs lxm3 launch launcher.py -- --config config/offline/cql.py --entrypoint d4rl_slim_benchmark.train --image d4rl-latest.si
f --launch_on_cluster True 
```

Error log: 
```bash
[13:49:42] Launching 36 jobs on beaker.cs.ucl.ac.uk                                                                                                                      gridengine.py:220
           Deployed archive to /home/danietan/lxm3-staging/projects/d4rl-slim-benchmark/archives/d4rl_slim_benchmark-20230927.134940.zip                                  artifacts.py:108
Uploading d4rl-latest.sif ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  12% 0:00:41 113.1 MB/s    
Traceback (most recent call last):                                                                                                                                                        
  File "/home/daniel/anaconda3/envs/lxm3/bin/lxm3", line 8, in <module>                                                                                                                   
    sys.exit(entrypoint())                                                                                                                                                                
  File "/home/daniel/lxm3/lxm3/cli/cli.py", line 104, in entrypoint                                                                                                                       
    app.run(main, flags_parser=_parse_flags)                                                                                                                                              
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/absl/app.py", line 308, in run                                                                                      
    _run_main(main, args) 
...
  File "/home/daniel/lxm3/lxm3/xm_cluster/execution/common.py", line 69, in create_array_job
    return _put_job_resources(
  File "/home/daniel/lxm3/lxm3/xm_cluster/execution/common.py", line 93, in _put_job_resources
    artifact.deploy_singularity_container(singularity_image)
  File "/home/daniel/lxm3/lxm3/xm_cluster/execution/artifacts.py", line 182, in deploy_singularity_container
    self._fs.ftp.put(
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_client.py", line 716, in putfo
    size = self._transfer_with_callback(
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_client.py", line 679, in _transfer_with_callback
    writer.write(data)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/file.py", line 389, in write
    self._write_all(data)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/file.py", line 507, in _write_all
    count = self._write(data)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_file.py", line 208, in _write
    t, msg = self.sftp._read_response(req)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
  File "/home/daniel/anaconda3/envs/lxm3/lib/python3.10/site-packages/paramiko/sftp_client.py", line 942, in _convert_status
    raise IOError(text)
OSError: Failure
```

This issue is probably related: https://github.com/paramiko/paramiko/issues/1000
Is it due to the way LXM3 uses paramiko to upload the singularity file?

**Comment by dtch1997** [comment] 2023-09-27 12:57
It turns out that the cause was something unrelated, but I'm leaving the issue up in case the issue with paramiko is relevant

**Comment by ethanluoyc** [comment] 2023-09-27 14:07
Closing as this issue is caused by cluster downtime.

**Closed by ethanluoyc** 2023-09-27 14:07 UTC
